# Generated by Django 5.2.7 on 2025-11-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_todomodel_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='checker',
            field=models.BooleanField(default=True),
        ),
    ]
