# Generated by Django 5.2.7 on 2025-11-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_todomodel_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='checker',
            field=models.BooleanField(default=False),
        ),
    ]
