# Generated by Django 5.2.7 on 2025-11-03 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_todomodel_is_hidden_alter_todomodel_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='timer',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
