# Generated by Django 5.2.7 on 2025-11-04 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_todomodel_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='todo_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
