# Generated by Django 5.2.7 on 2025-11-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_todomodel_todo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='every_day',
            field=models.JSONField(default=list),
        ),
    ]
