# Generated by Django 5.2.7 on 2025-11-06 11:44

from django.db import migrations




def creat_profiles(apps,schema_editor):
    User = apps.get_model('auth','User')
    UserProfile = apps.get_model('list','UserProfile')


    existing_profile_user_ids = UserProfile.objects.values_list('user_id',flat=True)

    profiles_to_create=[]
    for user in User.objects.exclude(id__in=existing_profile_user_ids):
        profiles_to_create.append(
            UserProfile(user=user)
        )
    if profiles_to_create:
        UserProfile.objects.bulk_create(profiles_to_create)
class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_remove_todomodel_every_day_userprofile'),
    ]

    operations = [
        migrations.RunPython(creat_profiles),
    ]
