# Generated by Django 5.2.7 on 2025-11-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_create_missing_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='is_everyday',
            field=models.BooleanField(default=False),
        ),
    ]
