# Generated by Django 5.2.7 on 2025-11-10 08:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_todomodel_is_everyday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='is_everyday',
        ),
        migrations.CreateModel(
            name='RecurringTodoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField(max_length=500)),
                ('todo_time', models.DurationField(default=datetime.timedelta(0))),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='todomodel',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='list.recurringtodotemplate'),
        ),
        migrations.AddIndex(
            model_name='todomodel',
            index=models.Index(fields=['to_user', 'is_hidden', '-created_at'], name='list_todomo_to_user_8f11ec_idx'),
        ),
        migrations.AddIndex(
            model_name='todomodel',
            index=models.Index(fields=['template'], name='list_todomo_templat_04120a_idx'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddIndex(
            model_name='recurringtodotemplate',
            index=models.Index(fields=['user', 'is_active'], name='list_recurr_user_id_4cd749_idx'),
        ),
    ]
